### ISSUE TITLE
Uncaught Error: Expected 'styles' to be an array of strings.

### ISSUE THREAD

**Issue by fstbraz** [surmon-china/ngx-quill-editor#23]
Installing on Angular 4. getting this error when webpack compiles for es5.

`compiler.es5.js:3920 Uncaught Error: Expected 'styles' to be an array of strings.
    at assertArrayOfStrings (compiler.es5.js:3920)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (compiler.es5.js:15174)
    at CompileMetadataResolver.loadDirectiveMetadata (compiler.es5.js:15096)
    at compiler.es5.js:26806
    at Array.forEach (<anonymous>)
    at compiler.es5.js:26805
    at Array.forEach (<anonymous>)
    at JitCompiler._loadModules (compiler.es5.js:26802)
    at JitCompiler._compileModuleAndComponents (compiler.es5.js:26772)
    at JitCompiler.compileModuleAsync (compiler.es5.js:26701)`

Any suggestion?

**Comment by rajsibi7** [comment]
I am working on two projects, one is angular 2 and another one is angular 4, in angular 2 projects it works fine but in angular 4 it throws the below error.
`Uncaught Error: Expected 'styles' to be an array of strings.
    at assertArrayOfStrings (compiler.es5.js:3351) [<root>]
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNonNormalizedDirectiveMetadata (compiler.es5.js:13775) [<root>]
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver._loadDirectiveMetadata (compiler.es5.js:13693) [<root>]
    at vendor.bundle.js:92249:54 [<root>]
    at Array.forEach (<anonymous>) [<root>]
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.loadNgModuleDirectiveAndPipeMetadata (compiler.es5.js:13916) [<root>]
    at vendor.bundle.js:103416:58 [<root>]
    at Array.forEach (<anonymous>) [<root>]
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._loadModules (compiler.es5.js:25083) [<root>]
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (compiler.es5.js:25037) [<root>]
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (compiler.es5.js:24999) [<root>]
    at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone (core.es5.js:4786) [<root>]
    at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule (core.es5.js:4772) [<root>]
    at Object.../../../../../src/main.ts (main.ts:11) [<root>]
﻿`
