### ISSUE TITLE
Testing wih Jest fails.

### ISSUE THREAD

**Issue by 1ik** [surmon-china/ngx-quill-editor#30]
The following block of code is causing a failure when I am using Jest with jest-angular-preset plugin.

https://github.com/surmon-china/ngx-quill-editor/blob/512310bf02f5003d885f9ef9711c325605f3c7f5/quillEditor.component.ts#L20-L25

The details of the error is,
```
 FAIL  src/app/app.component.spec.ts (5.944s)
  AppComponent
    ✕ should create the app (96ms)

  ● AppComponent › should create the app

    SyntaxError: The string did not match the expected pattern.

      at XMLHttpRequest.open [as __zone_symbol__open] (node_modules/jest-preset-angular/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:475:15)
      at Array.map (native)

  ● AppComponent › should create the app

    SyntaxError: The string did not match the expected pattern.

      at XMLHttpRequest.open [as __zone_symbol__open] (node_modules/jest-preset-angular/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:475:15)
      at Array.map (native)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        7.915s
Ran all test suites.
```

However, the error can be easily fixed if it's changed to inline like the following,
```
styleUrls: [
    './quillEditor.component.css', '../quill/dist/quill.core.css', '../quill/dist/quill.snow.css', '../quill/dist/quill.bubble.css'
  ],
```

I know this is jest-angular-preset's plugins regex that fails to parse the line breaks but if you think that little change in code won't hurt I can create a PR :).

**Comment by Triptophan** [comment]
I receive the same issue when using a templateUrl in my component

`@Component({
    templateUrl: 'breaker-lockout-finder.html'
})`

Get the error:
`Component: BreakerLockoutFinderPage › is created

    SyntaxError: The string did not match the expected pattern.

      at XMLHttpRequest.open [as __zone_symbol__open] (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:482:15)
      at node_modules/zone.js/dist/zone.js:2238:31
      at XMLHttpRequest.proto.(anonymous function) (node_modules/zone.js/dist/zone.js:1425:20)
      at ResourceLoaderImpl.Object.<anonymous>.ResourceLoaderImpl.get (node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js:42:13)
      at DirectiveNormalizer.Object.<anonymous>.DirectiveNormalizer._fetch (node_modules/@angular/compiler/bundles/compiler.umd.js:13297:45)
      at DirectiveNormalizer.Object.<anonymous>.DirectiveNormalizer.normalizeTemplateAsync (node_modules/@angular/compiler/bundles/compiler.umd.js:13352:21)
      at DirectiveNormalizer.Object.<anonymous>.DirectiveNormalizer.normalizeTemplate (node_modules/@angular/compiler/@angular/compiler.es5.js:13319:39)
      at CompileMetadataResolver.Object.<anonymous>.CompileMetadataResolver._loadDirectiveMetadata (node_modules/@angular/compiler/@angular/compiler.es5.js:14250:44)
      at node_modules/@angular/compiler/@angular/compiler.es5.js:14446:54
          at Array.forEach (<anonymous>)`
