### ISSUE TITLE
AOT issue

### ISSUE THREAD

**Issue by erashu212** [surmon-china/ngx-quill-editor#50]
Hi,

```
ERROR in E:\Projects\abc\v1\node_modules\ngx-quill-editor\quillEditor.component.css:71
throw new Error("Module build failed: Error: \"extract-text-webpack-plugin\" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example\n    at Object.pitch (E:\\Projects\\abc\\v1\\node_modules\\extract-text-webpack-plugin\\dist\\loader.js:57:11)");
^

Error: Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.pitch (E:\Projects\abc\v1\node_modules\extract-text-webpack-plugin\dist\loader.js:57:11)
    at Object.sVlT (E:\Projects\abc\v1\node_modules\ngx-quill-editor\quillEditor.component.css:71:7)
    at __webpack_require__ (E:\Projects\abc\v1\node_modules\ngx-quill-editor\quillEditor.component.css:20:30)
    at sVlT (E:\Projects\abc\v1\node_modules\ngx-quill-editor\quillEditor.component.css:63:18)
    at E:\Projects\abc\v1\node_modules\ngx-quill-editor\quillEditor.component.css:66:10
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.runInNewContext (vm.js:93:38)
    at WebpackResourceLoader._evaluate (E:\Projects\abc\v1\node_modules\@ngtools\webpack\src\resource_loader.js:110:40)
    at Compilation.compilation.plugin (E:\Projects\abc\v1\node_modules\@ngtools\webpack\src\resource_loader.js:58:26)
    at Compilation.applyPluginsAsyncSeries (E:\Projects\abc\v1\node_modules\tapable\lib\Tapable.js:206:13)
```

I am facing this. Any help would be appreciated.

**Comment by erashu212** [comment]
This has been fixed by moving css file reference from .angular-cli.json to style.css
