### ISSUE TITLE
Angular 6 Package format compliance

### ISSUE THREAD

**Issue by josephharveyangeles** [surmon-china/ngx-quill-editor#55]
Just upgraded our application, I'm getting this error on runtime:

```javascript
ERROR in ./node_modules/ngx-quill-editor/index.ts
Module build failed: Error: /path-to-app/node_modules/ngx-quill-editor/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/jangeles/Codespace/marshall-space/marshall-ce/src/frontend/node_modules/@ngtools/webpack/src/packages/ngtools/webpack/src/angular_compiler_plugin.ts:920:15)
    at plugin.done.then (/home/jangeles/Codespace/marshall-space/marshall-ce/src/frontend/node_modules/@ngtools/webpack/src/packages/ngtools/webpack/src/loader.ts:49:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/page/preview/keywords-and-descriptions/keywords-and-descriptions-preview.component.spec.ts 26:0-53 148:16-33
 @ ./src sync \.spec\.ts$
 @ ./src/test.ts
```

any chance that this will get sorted out?

**Comment by kmorales13** [comment]
Repo hasn't been updated in a while, you can get around this by adding it to the `include` property:
```
"include": [
    "src/**/*",
    "node_modules/ngx-quill-editor/*"
  ]
```

**Comment by nimatullah** [comment]
@kmorales13, I have the same problem. It did not helped me.

**Comment by Artaud** [comment]
@kmorales13 Thanks a big bunch, it helped me!

**Comment by syedzahed** [comment]
### Include quill editor in **tsconfig.app.json** like this

```javascript
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": []
  },
  "include": [
    "src/**/*.ts",
    **"node_modules/ngx-quill-editor"**
  ],
  "exclude": [
    "src/test.ts",
    "src/**/*.spec.ts"
  ]
}```
